/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/home/home" |
       "/pages/login/login" |
       "/pages/login/loginOauth2" |
       "/pages/workHome/workHome" |
       "/pages-home/about/about" |
       "/pages-home/annotation/annotationDetail" |
       "/pages-home/annotation/annotationList" |
       "/pages-home/annotation/myNewsList" |
       "/pages-home/demo/demo" |
       "/pages-home/demo/form" |
       "/pages-home/demo/indexBar" |
       "/pages-home/demo/selectPicker" |
       "/pages-home/demo/tree" |
       "/pages-home/home/home" |
       "/pages-home/more/more" |
       "/pages-message/chat/chat" |
       "/pages-message/chat/chatRecord" |
       "/pages-message/chat/chatSetting" |
       "/pages-message/contacts/contacts" |
       "/pages-message/moreFunction/moreFunction" |
       "/pages-message/myDepart/myDepart" |
       "/pages-message/myGroup/addGroup" |
       "/pages-message/myGroup/groupPage" |
       "/pages-message/myGroup/myGroup" |
       "/pages-message/personPage/personPage" |
       "/pages-message/tenant/tenant" |
       "/pages-user/location/location" |
       "/pages-user/organization/organization" |
       "/pages-user/organization/rightTypeChange" |
       "/pages-user/password/password" |
       "/pages-user/userDetail/userDetail" |
       "/pages-user/userEdit/userEdit" |
       "/pages-work/dragPage/index" |
       "/pages-work/onlinePage/onlineAdd" |
       "/pages-work/onlinePage/onlineDetail" |
       "/pages-work/onlinePage/onlineEdit" |
       "/pages-sub/online/online" |
       "/pages-sub/online/onlineCard" |
       "/pages-sub/online/onlineTable" |
       "/pages-sub/vpn/vpn-android" |
       "/pages-sub/vpn/vpn-harmony" |
       "/pages-sub/vpn/vpn-ios" |
       "/pages-sub/webLink/webLink";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
